doc: 'Manage a Go application'

extends:
- ~/.neon/c4s4/misc/buildir.yml
- ~/.neon/c4s4/misc/changelog.yml
- ~/.neon/c4s4/go/libs.yml

properties:
  NAME: ~

environment:
  GOPATH: '#{_BASE}'
  PATH:   '#{_BASE}/bin:${PATH}'

targets:

  format:
    doc: 'Format Go code'
    steps:
    - 'go fmt #{NAME}'

  test:
    doc: 'Run unit tests'
    steps:
    - 'go test #{NAME}/...'
