# Neon build file (http://github.com/c4s4/neon)
# 
# You must configure SAXON_HOME and XSPEC_HOME with path to these tools.
# Target xspec calls xspec-status (http://github.com/c4s4/xspec-status).

extends:
- c4s4/build/xslt.yml

properties:
  NAME:       'name'
  VERSION:    '1.0.0'
  SAXON_HOME: ~
  XSPEC_HOME: ~
